GdbmError: keep the associated system error where appropriate
* README.md: Document new features.
* gdbm.go (GdbmError): Store the associated system error, if any.
(LastGdbmError): Remove.
(NewGdbmError): New function.
(Error): Append associated system error diagnostics, if any.
(SysError): New method.
(Is): Match system errors as well.
* gdbm_test.go: Use t.Fatal instead of t.Error where appropriate.
Test error codes.